# Tomcat
server:
  port: 9001

# Spring
spring:
  application:
    # 应用名称
    name: pr-gateway-9001
  cloud:
    nacos:
      discovery:
        # 服务注册地址
        server-addr: 127.0.0.1:8848
    gateway:
      enabled: true # 开启网关服务
      discovery: # 服务发现配置
        locator:
          enabled: true # 自动依据nacos中的服务id生成路由
          lower-case-service-id: true #　小写服务id
      routes:
        - id: project-manage
          uri: lb://project-manage-9003 #找到在nacos上相同服务名的ip
          predicates:
            - Path=/project/** #匹配后提供服务的路由地址
        - id: data-collection
          uri: lb://data-collection-9007 #找到在nacos上相同服务名的ip
          predicates:
            - Path=/dataCollection/** #匹配后提供服务的路由地址
        - id: pr-manage
          uri: lb://pr-manage-9002 #找到在nacos上相同服务名的ip
          predicates:
            - Path=/** #匹配后提供服务的路由地址

