server:
  port: 9004
spring:
  application:
    name: pr-sorting-engine-9004
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        # 配置sentinel dashboard地址
        dashboard: 127.0.0.1:8080
        # 默认8719端口，若被占用，则每次+1进行查找
        port: 8718
  datasource:
    dynamic:
      primary: base
      datasource:
        base:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/project_time_task_db?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: root

management:
  endpoint:
    web:
      exposure:
        include: '*'
    env:
      post:
        enabled: true
mybatis-plus:
  type-aliases-package: com.jjyu.entity
  mapper-locations: classpath*:/mapper/**.xml
  configuration:
    jdbc-type-for-null: null
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭
  global-config:
    banner: false